/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-125148-g20054712a2-g9cbd889670+3"
#endif /* AVUTIL_FFVERSION_H */
