#pragma once

namespace media::ffmpeg::graph {

enum class MediaEdgeKind {
    Unknown,

    /* Compressed packet read from demuxer or realtime packet source. */
    InputPacket,

    /* Generic decoded frame when hardware/software ownership is not fixed yet. */
    RawFrame,

    /* Hardware-backed frame, for example D3D11VA, CUDA, VAAPI, DRM_PRIME, or RKMPP. */
    HardwareFrame,

    /* CPU-readable software frame. */
    SoftwareFrame,

    /* Packet generated by an encoder. */
    EncodedPacket,

    /* Packet forwarded without decoding/re-encoding. */
    CopiedPacket,

    /* Packet or byte stream after muxing/containerization. */
    MuxedPacket,

    /* Stream, codec, time-base, hardware, or layout metadata. */
    Metadata,

    /* EOF, flush, stop, trailer, and other lifecycle/control signals. */
    Control,

    /* Diagnostic or tracing event edge. */
    Event
};

} // namespace media::ffmpeg::graph
